# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sniffer-HTTP
version:      0.16
version_from: lib/Sniffer/HTTP.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Data::Inheritable:      0
    Exporter::Lite:                0
    HTTP::Request:                 0
    LWP::Simple:                   0
    Net::Pcap:                     0.09
    NetPacket::TCP:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
